name: Generate SBOM and Run SAST for Juice Shop

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-syft:
    name: Build & SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t juice-shop:${{ github.sha }} .

      - name: Syft SBOM Scan
        uses: anchore/sbom-action@v0
        with:
          image: "juice-shop:${{ github.sha }}"
          output-file: "sbom.spdx.json"
          format: "spdx-json"

  # 2) SAST (Semgrep) Job
  Sast-scan:
    name: SAST (Semgrep)
    needs: build-and-syft
    runs-on: ubuntu-latest
    container: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semgrep Scan
        run: |
         mkdir -p semgrep/results
         semgrep ci --config=auto --sarif --output=semgrep/results/semgrep.sarif || true

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'semgrep/results/semgrep.sarif'
          
      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-results
          path: semgrep/results/

  # 3) Gitleaks-scan Job
  Gitleaks-scan:
    name: Gitleaks (Secret)
    needs: Sast-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SecretScan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true
        continue-on-error: true

      - name: Upload
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'results.sarif'

      - name: Upload gitleaks report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results.sarif
          path: .

  # 5) Deploy Job (Dummy)
  deploy:
    name: Deploy App Production
    needs:  Gitleaks-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dummy Deploy Step
        run: echo "Deploying app... (This is a dummy step)"
